### ISSUE TITLE
Keep cursor position in vmd window same with emacs window

### ISSUE THREAD

**Issue by hiberabyss** [blak3mill3r/vmd-mode#11]
Thanks for your plugin, it's very useful!

I'm curious if it's possible to keep the cursor position in vmd window same with emacs window, the content in vmd could scroll automatically while cursor move through emacs window.

**Comment by blak3mill3r** [comment]
@hiberabyss I like that idea, I think it would be really nice to have.

`vmd-mode` is a thin wrapper around `vmd` https://github.com/yoshuawuyts/vmd which does all the real work, and since that project does not support anything that would allow us to set the cursor position with `vmd-mode`, this cannot be done without modifying `vmd`.

It might be a generally useful feature for `vmd` though, you might consider posting an issue there.
