### ISSUE TITLE
Feature Request: A way to render latex with Mathjax or any other way

### ISSUE THREAD

**Issue by therimalaya** [blak3mill3r/vmd-mode#12]
It is itself a great product. It would be nice if it can render LaTeX using MathJax or any other means.

**Comment by blak3mill3r** [comment]
Thanks. I agree, I would love to see LaTex/MathJax support. It doesn't exist in `vmd` itself, since this emacs plugin defers all the real markdown rendering work to `vmd` (an `npm` package), it is not easily within reach. This may be partly because `vmd` is trying to mimic Github's own Markdown rendering, which does not support LaTex.

I have considered reimplementing `vmd` which has a few other problems, and if I were to do so I would probably add MathJax... but it is not high on my priority list.
