### ISSUE TITLE
Unable to use it on Mac

### ISSUE THREAD

**Issue by ethanluoyc** [blak3mill3r/vmd-mode#8]
Hi, 

It is a really nice piece of integration here! But unfortunately I am unable to run it on my Mac cuz as soon as I enter `vmd-mode` Electron will crash.

Any idea how I might be able to fix this?

**Comment by blak3mill3r** [comment]
Hi,

I haven't tried running it on a mac. Does `vmd` itself work? Just start it like `vmd somefile.md` and then start saving changes to that file.

If `vmd` on its own does not work, it could be a bug in either `vmd` or `electron`. If it does, I'm at a loss to understand why it fails to work with this integration (nothing in the elisp code is platform-specific as far as I know). I do not have access to a Mac to test it.

**Comment by ethanluoyc** [comment]
Hi, vmd works in the command line. I've tested it, the problem is with the (start-process) function, soon as it hits this function, it will crash for reasons that I cannot understand. 
It's best if we can have another Mac user to reproduce this.

Sent from my iPhone, sorry for the brevity.

On Fri, Jul 15, 2016 at 4:20 AM +0800, "Blake Miller" notifications@github.com wrote:

Hi,

I haven't tried running it on a mac. Does vmd itself work? Just start it like vmd somefile.md and then start saving changes to that file.

If vmd on its own does not work, it could be a bug in either vmd or electron. If it does, I'm at a loss to understand why (nothing in the elisp code is platform-specific as far as I know). I do not have access to a Mac to test it.

**Comment by blak3mill3r** [comment]
Okay, I'll ask a coworker to try it out on a mac, and see what we find. I'll get back to you.

**Comment by blak3mill3r** [comment]
Okay, I've reproduced the issue. I don't have a mac, but at some point I might have the opportunity to investigate this on someone else's...

**Comment by chiumarco** [comment]
Hi,
After adding below path into my init.el file, I can run it on my Mac. 

(setenv "PATH" (concat "/usr/local/bin:/usr/bin:" (getenv "PATH")))
(setq exec-path (append '("/usr/local/bin" "/usr/bin") exec-path))

**Comment by blak3mill3r** [comment]
Emacs by default does not inherit the `PATH` from a shell that launches it, which IMO is confusing and not a sensible default.

There is this package https://github.com/purcell/exec-path-from-shell which changes that behavior so that emacs inherits `PATH` from the shell. I am guessing that this would also fix the issue on a Mac since the last line of @chiumarco 's fix is also doing something similar. In fact, I use `exec-path-from-shell` and also `nvm` and `npm` (which will install `vmd` somewhere that would not be on the emacs `exec-path` by default) ... so perhaps this issue is not Mac specific at all, but would occur whenever `vmd` is not on `exec-path`...
